---
- name: This playbook help us to learn the Arithmetic Operators
  hosts: local
  gather_facts: false
  vars:
    x: 15
    y: 2.5
  tasks:
    - name: We will doing maths calculations
      ansible.builtin.debug:
        msg:
          - "The addition of x and y is: {{ x + y }}"
          - "The substraction of x and y is: {{ x - y }}"
          - "The multiplication of x and y is: {{ x * y }}"
          - "The division of x and y is: {{ x / y }}"
          - "The modulus of x and y is: {{ x % y }}"
          - "The addition of a and b is: {{ a + b }}"
          - "The substraction of a and b is: {{ a - b }}"
          - "The multiplication of a and b is: {{ a * b }}"
          - "The division of a and b is: {{ a / b }}"
          - "The modulus of a and b is: {{ a % b }}"
