---
- name: This playbook help us to learn methods and filters
  hosts: localhost
  gather_facts: false
  vars:
    name: mUtHO
  tasks:
    - name: Demo of filter methods
      ansible.builtin.debug:
        msg:
          - "The value of name in upper case is {{ name | upper }}"
          - "The value of name in lower case is {{ name | lower }}"
          - "The value of name in title case is {{ name | title }}"
          - "The value of name in title case is {{ name | title() }}"
          - "The value of name with replaced 'O' to '0' is {{ name | replace('O', '0') }}"
