---
- name: This playbook help us to learn methods and filters
  hosts: localhost
  gather_facts: false
  vars:
    name: mUtHO
  tasks:
    - name: Demo of filter methods
      ansible.builtin.debug:
        msg:
          - "The value of x in upper case is {{ x | upper }}"
          - "The value of x in lower case is {{ x | lower }}"
          - "The value of x in title case is {{ x | title }}"
          - "The value of x in title case is {{ x | title() }}"
          - "The value of x with replaced 'O' to '0' is {{ x | replace('O', '0') }}"
