---
- name: Install software based on OS family
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: Install the package using yum
      ansible.builtin.yum:
        name: nginx
        state: present
      when: ansible_facs.os_family == 'RedHat'
    - name: Install the package using apt
      ansible.builtin.apt:
        name: nginx
        state: present
      when: ansible_facs.os_family == 'Debian'
