---
- name: Install software based on OS family
  hosts: all
  gather_facts: true
  become: true
  vars_prompt:
    - name: software_name
      prompt: "Enter the software name"
      private: false
  tasks:
    - name: Install the package using yum
      ansible.builtin.yum:
        name: { { software_name } }
        state: present
        update_cache: true
      when: ansible_facts.os_family == 'RedHat'
    - name: Install the package using apt
      ansible.builtin.apt:
        name: { { software_name } }
        state: present
        update_cache: true
      when: ansible_facts.os_family == 'Debian'
