---
- name: Playbook for loop
  hosts: localhost
  gather_facts: false
  vars:
    files:
      - config
      - config.d
      - config.txt
  tasks:
    - name: Creating a file
      ansible.builtin.file:
        path: "/tmp/{{ item }}"
        state: touch
