---
- name: Playbook for template demo
  hosts: localhost
  gather_facts: false
  become: true
  tasks:
    - name: Install httpd Package
      ansible.builtin.package:
        name: httpd
        state: present
        update_cache: yes
      ignore_errors: true
    - name: Start httpd service
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true
    - name: Copy file using jinja2 template
      ansible.builtin.template:
        src: index.j2
        dest: /var/www/html/index.html
  handlers:
    - name: Restart httpd
      ansible.builtin.service:
        name: httpd
        state: started
