---
  - name: Getting input from the user
    hosts: localhost
    gather_facts: false
    vars_prompt:
      - name: x
        prompt: "Enter the value of x"
        private: no
      - name: y
        prompt: "Enter the value of y"
        private: yes
    tasks:
      - name: Display the value of x
        ansible.builtin.debug:
          msg: "The value of x is {{ x }}"
      - name: Display the value of y
        ansible.builtin.debug:
          msg: "The value of y is {{ y }}"