---
- name: Register the output
  hosts: local
  gather_facts: false
  tasks:
    - name: Getting the uname value
      ansible.builtin.command: "uname"
      register: unameout

    - name: Printing the uname value
      ansible.builtin.debug:
        msg: "{{ unameout }}"
