---
  - name: Demo for show facts
    hosts: local
    gather_facts: false
    vars:
      x: 10
      y: 15
    tasks:
      - name: Priting the vars value
        ansible.builtin.debug:
          msg:
            - "The value of x is {{ x }}"
            - "The value of y is {{ y }}"

      - name: Change the value of x an y
        ansible.builtin.set_fact:
          x: 150
          y: 130
      
      - name: Priting the changed value
        ansible.builtin.debug:
          msg:
            - "The value of x is {{ x }}"
            - "The value of y is {{ y }}"